### ISSUE TITLE
ndt installs old version of nitor-vault

### ISSUE THREAD

**Issue by hynynen** [NitorCreations/nameless-deploy-tools#1]
Installing nameless-deploy-tools with pip installs old version of nitor-vault. This results in a conflict with package threadlocal-aws version.

On Windows server 2016 in AWS, only python3.7 installed by Chocolatey (ndt bake-win-image):

1. pip install -U nameless-deploy-tools awscli boto3
2.
```powershell
PS C:\Users\Administrator> ndt account-id
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (threadlocal-aws 0.2 (c:\python37\lib\site-packages), Requirement.parse('threadlocal-aws==0.6'), {'ec2-utils'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Scripts\ndt-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3241, in <module>
    @_call_aside
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python37\lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'threadlocal-aws==0.6' distribution was not found and is required by ec2-utils
PS C:\Users\Administrator> pip install -U nitor-vault
Collecting nitor-vault
  Downloading https://files.pythonhosted.org/packages/86/16/3fed746f6fd1b134778ac04a28ef3dddebd1a43d2cb5077e90871c1697c9/nitor-vault-0.38.tar.gz
Collecting threadlocal-aws==0.6 (from nitor-vault)
  Downloading https://files.pythonhosted.org/packages/98/0b/621bc18b04d19438ac3c64015a3dd775b79fb1b89521ad8b73397b8248fe/threadlocal-aws-0.6.tar.gz
Requirement already satisfied, skipping upgrade: requests in c:\python37\lib\site-packages (from nitor-vault) (2.22.0)
Requirement already satisfied, skipping upgrade: argcomplete in c:\python37\lib\site-packages (from nitor-vault) (1.10.0)
Requirement already satisfied, skipping upgrade: future in c:\python37\lib\site-packages (from nitor-vault) (0.17.1)
Requirement already satisfied, skipping upgrade: cryptography in c:\python37\lib\site-packages (from nitor-vault) (2.7)
Requirement already satisfied, skipping upgrade: win-unicode-console in c:\python37\lib\site-packages (from nitor-vault) (0.5)
Requirement already satisfied, skipping upgrade: wmi in c:\python37\lib\site-packages (from nitor-vault) (1.4.9)
Requirement already satisfied, skipping upgrade: pypiwin32 in c:\python37\lib\site-packages (from nitor-vault) (223)
Requirement already satisfied, skipping upgrade: boto3 in c:\python37\lib\site-packages (from threadlocal-aws==0.6->nitor-vault) (1.9.183)
Requirement already satisfied, skipping upgrade: urllib3 in c:\python37\lib\site-packages (from threadlocal-aws==0.6->nitor-vault) (1.25.3)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\python37\lib\site-packages (from requests->nitor-vault) (2.8)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\python37\lib\site-packages (from requests->nitor-vault) (2019.6.16)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\python37\lib\site-packages (from requests->nitor-vault) (3.0.4)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in c:\python37\lib\site-packages (from cryptography->nitor-vault) (1.12.3)
Requirement already satisfied, skipping upgrade: six>=1.4.1 in c:\python37\lib\site-packages (from cryptography->nitor-vault) (1.12.0)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in c:\python37\lib\site-packages (from cryptography->nitor-vault) (0.24.0)
Requirement already satisfied, skipping upgrade: pywin32>=223 in c:\python37\lib\site-packages (from pypiwin32->nitor-vault) (224)
Requirement already satisfied, skipping upgrade: s3transfer<0.3.0,>=0.2.0 in c:\python37\lib\site-packages (from boto3->threadlocal-aws==0.6->nitor-vault) (0.2.1)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in c:\python37\lib\site-packages (from boto3->threadlocal-aws==0.6->nitor-vault) (0.9.4)
Requirement already satisfied, skipping upgrade: botocore<1.13.0,>=1.12.183 in c:\python37\lib\site-packages (from boto3->threadlocal-aws==0.6->nitor-vault) (1.12.183)
Requirement already satisfied, skipping upgrade: pycparser in c:\python37\lib\site-packages (from cffi!=1.11.3,>=1.8->cryptography->nitor-vault) (2.19)
Requirement already satisfied, skipping upgrade: docutils>=0.10 in c:\python37\lib\site-packages (from botocore<1.13.0,>=1.12.183->boto3->threadlocal-aws==0.6->nitor-vault) (0.14)
Requirement already satisfied, skipping upgrade: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in c:\python37\lib\site-packages (from botocore<1.13.0,>=1.12.183->boto3->threadlocal-aws==0.6->nitor-vault) (2.8.0)
Installing collected packages: threadlocal-aws, nitor-vault
  Found existing installation: threadlocal-aws 0.2
    Uninstalling threadlocal-aws-0.2:
      Successfully uninstalled threadlocal-aws-0.2
  Running setup.py install for threadlocal-aws ... done
  Found existing installation: nitor-vault 0.35
    Uninstalling nitor-vault-0.35:
      Successfully uninstalled nitor-vault-0.35
  Running setup.py install for nitor-vault ... done
Successfully installed nitor-vault-0.38 threadlocal-aws-0.6
PS C:\Users\Administrator> ndt account-id
Traceback (most recent call last):
  File "C:\Python37\Scripts\ndt-script.py", line 11, in <module>
    load_entry_point('nameless-deploy-tools==1.91', 'console_scripts', 'ndt')()
  File "c:\python37\lib\site-packages\n_utils\ndt.py", line 121, in ndt
    my_func = getattr(__import__(parts[0], fromlist=[parts[1]]),
  File "c:\python37\lib\site-packages\ec2_utils\cli.py", line 13, in <module>
    from ec2_utils import ebs, instance_info, interface, logs, utils
  File "c:\python37\lib\site-packages\ec2_utils\interface.py", line 160, in <module>
    libc = ctypes.CDLL(ctypes.util.find_library('c'))
  File "c:\python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
PS C:\Users\Administrator>
```
There is another error in the end, I don't know where that comes from but it seems to be another issue.

**Comment by psiniemi** [comment]
That probably only applies if there is an older version of vault already installed - it just fails to upgrade it. Otherwise it would always install the latest vault. Anyway added a version that has the same requirement for threadlocal-aws.
