### ISSUE TITLE
ModuleNotFoundError: No module named 'wmi'

### ISSUE THREAD

**Issue by Jalle19** [NitorCreations/nameless-deploy-tools#18]
Our Windows deploy jobs where failing for unknown reasons, and it seems to be caused by this:

```
PS C:\Users\Administrator>  pip3 show nameless-deploy-tools
Name: nameless-deploy-tools
Version: 1.239
Summary: Tools for deploying to AWS via CloudFormation and Serverless framework that support a pull request based workfl
ow
Home-page: http://github.com/NitorCreations/nameless-deploy-tools
Author: Pasi Niemi
Author-email: pasi@nitor.com
License: Apache 2.0
Location: c:\python37\lib\site-packages
Requires: argcomplete, boto3, cloudformation-utils, configparser, ec2-utils, future, ipaddr, jmespath, nitor-vault, pyam
l, pycryptodomex, Pygments, pyOpenSSL, pyotp, pyqrcode, python-dateutil, PyYAML, requests, scandir, six, termcolor
Required-by:
PS C:\Users\Administrator> vault -l dev-admin
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\vault.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\n_vault\cli.py", line 137, in main
    vault_region=args.region)
  File "c:\python37\lib\site-packages\n_vault\vault.py", line 472, in __init__
    vault_region = region()
  File "c:\python37\lib\site-packages\threadlocal_aws\__init__.py", line 93, in region
    elif is_ec2():
  File "c:\python37\lib\site-packages\threadlocal_aws\__init__.py", line 105, in is_ec2
    import wmi
ModuleNotFoundError: No module named 'wmi'
```

**Comment by psiniemi** [comment]
Strange, wmi is a windows-only dependency and has been for a long time. For some reason the install doesn't pull it. A quick workaround is to install the 'wmi' module separately before vault is needed.

**Comment by psiniemi** [comment]
Maybe I just need to transition all these projects to pyproject.toml: http://ivory.idyll.org/blog/2021-transition-to-pyproject.toml-example.html

**Comment by Jalle19** [comment]
> A quick workaround is to install the 'wmi' module separately before vault is needed.

That's what we ended up doing AFAIK.

**Comment by Jalle19** [comment]
Moving the discussion to https://github.com/NitorCreations/vault/pull/48
